### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by tomitrescak** [laco0416/light-ts-loader#6]
Hi, I found your loader in the survivejs book. On the first try the build time is 50% then already fast awesome typescript loader.

Yet, the compilation does not proceed well  and I have some errors in console such as this:

```
ERROR in ./src/shared/helpers/class_helpers.ts
Module parse failed: /Users/tomi/Github/packages/webpack2-typescript/node_modules/light-ts-loader/index.js!/Users/tomi/Github/packages/webpack2-typescript/src/shared/helpers/class_helpers.ts Unexpected token (17:12)
You may need an appropriate loader to handle this file type.
|                 arr1.push({ value: arr[i], index: i, nextIndex: i + 1 }),
|                 "}" + " " + "return arr1;" + " " + "} else ",
|             ,
|                 " (let i = 0; i ",
|                 React.createElement(arr.length, null),
 @ ./src/client/configs/state.ts 17:0-62
 @ ./src/client/configs/context.tsx
 @ ./src/client/index.ts
 @ multi ./src/shared/metadata react-hot-loader/patch webpack-hot-middleware/client webpack/hot/only-dev-server ./src/client/index.ts
```

Do you have any idea why the code does not compile with light-ts-loader?

1. It compiles with tsc
2. It compiles with awesome-typescript-loader
3. It compiles with ts-loader

**Comment by lacolaco** [comment]
If you can, I'd like to see your `class_helpers.ts`, `./src/client/configs/state.ts` and `./src/client/configs/context.tsx`. 

IMO, it's caused by TSX. Are you using diamond-cast (`<Foo>` ) with TSX?

**Comment by tomitrescak** [comment]
Hello, here you go as promised:

https://gist.github.com/tomitrescak/75d9f158c48124431b3a3b989bb93f02

**Comment by lacolaco** [comment]
@tomitrescak Thank you. 
Could you try rewriting as the below? Then please let me know the result.

![image](https://cloud.githubusercontent.com/assets/1529180/22638195/e7ee67a4-ec89-11e6-865c-e8795362939a.png)

**Comment by tomitrescak** [comment]
Yes, that seemed to do the trick. Compiler treats ts files as tsx.
